#!/bin/bash
# Build Personal OS Studio into a launchable macOS .app bundle.
set -e
cd "$(dirname "$0")"

APP_NAME="Personal OS Studio"
BUNDLE_ID="com.dretech.PersonalOSStudio"
BIN_NAME="PersonalOSStudio"
BUILD_DIR=".build/release"
APP_DIR="dist/${APP_NAME}.app"

echo "▸ Compiling (release)…"
swift build -c release

echo "▸ Assembling bundle…"
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR/Contents/MacOS" "$APP_DIR/Contents/Resources"
cp "$BUILD_DIR/$BIN_NAME" "$APP_DIR/Contents/MacOS/$BIN_NAME"

cat > "$APP_DIR/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>${APP_NAME}</string>
    <key>CFBundleDisplayName</key><string>${APP_NAME}</string>
    <key>CFBundleExecutable</key><string>${BIN_NAME}</string>
    <key>CFBundleIdentifier</key><string>${BUNDLE_ID}</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>1.0.0</string>
    <key>CFBundleVersion</key><string>1</string>
    <key>LSMinimumSystemVersion</key><string>14.0</string>
    <key>NSHighResolutionCapable</key><true/>
    <key>NSPrincipalClass</key><string>NSApplication</string>
    <key>CFBundleIconFile</key><string>AppIcon</string>
    <!-- Allow cleartext HTTP to localhost (Ollama on :11434). Cloud providers use HTTPS. -->
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsLocalNetworking</key><true/>
    </dict>
</dict>
</plist>
PLIST

# Icon (optional) — generated by make-icon.sh if present.
if [ -f "dist/AppIcon.icns" ]; then
    cp "dist/AppIcon.icns" "$APP_DIR/Contents/Resources/AppIcon.icns"
fi

# Code signature. Prefer a stable local identity when one exists — ad-hoc signing
# changes the signature every build, so macOS forgets Keychain "Always Allow" grants
# and re-prompts for API/vault keys after each rebuild. Create one once with
# Keychain Access → Certificate Assistant → Create a Certificate…
# (name: "Personal OS Studio Dev", type: Code Signing), and this picks it up.
IDENTITY="Personal OS Studio Dev"
if security find-identity -v -p codesigning 2>/dev/null | grep -q "$IDENTITY"; then
    codesign --force --deep --sign "$IDENTITY" "$APP_DIR" 2>/dev/null \
        && echo "▸ Signed with stable identity: $IDENTITY" \
        || codesign --force --deep --sign - "$APP_DIR" 2>/dev/null
else
    codesign --force --deep --sign - "$APP_DIR" 2>/dev/null || echo "  (codesign skipped)"
fi

echo "▸ Built: $APP_DIR"
echo "  Launch with:  open \"$APP_DIR\""
