import Foundation

/// Implements the OpenClaw adapter documented in
/// `agent_os/adapters/openclaw.md` (pinned 2026.2.x). Transforms canonical
/// Agent OS Markdown into the workspace files OpenClaw reads at session start:
/// SOUL.md, AGENTS.md, skills/<name>/SKILL.md, MEMORY.md, memory/<name>.md.
///
/// First plug-in of the `HarnessAdapter` framework: the mapping below is
/// OpenClaw-specific; shared transform rules live in `AdapterHelpers`.
struct OpenClawAdapter: HarnessAdapter {

    let harnessID = "openclaw"

    /// Injected at registration (AppState) so the delivery can reach the live
    /// OpenClawService for workspace discovery. Defaults to an empty descriptor
    /// for headless/self-test use, where delivery is irrelevant.
    var delivery: DeliveryKind

    init(delivery: DeliveryKind = .directory(DirectoryDelivery(
        targetLabel: "Target workspace",
        discoverTargets: { [] },
        noTargetGuidance: "Configure OpenClaw in settings.",
        postPush: nil,
        healthProbe: nil))) {
        self.delivery = delivery
    }

    // MARK: Public entry point

    func build(from store: CanonicalStore) -> BuildResult {
        var result = BuildResult()

        buildSoul(from: store, into: &result)
        buildAgents(from: store, into: &result)
        buildSkills(from: store, into: &result)
        buildMemory(from: store, into: &result)
        noteConnections(from: store, into: &result)

        if result.artifacts.isEmpty {
            result.warnings.append("Nothing selected to build. Check at least one Identity, Context, Skill, or Memory file in the browser.")
        }
        return result
    }

    // MARK: Identity → SOUL.md

    private func buildSoul(from store: CanonicalStore, into result: inout BuildResult) {
        let identities = store.includedFiles(.identity)
        guard let file = identities.first else {
            result.warnings.append("No Identity file selected — SOUL.md not generated. Identity is the foundation layer.")
            return
        }
        if identities.count > 1 {
            result.warnings.append("Multiple Identity files selected; only \(file.filename) was used for SOUL.md.")
        }

        let raw = store.read(file)
        let (fields, body) = Frontmatter.split(raw)
        let parsed = MarkdownSections.parse(body)

        var out = ""
        out += AdapterHelpers.bannerOrDefault(parsed.banner, designation: file.designation) + "\n"
        out += AdapterHelpers.provenanceComment(fields) + "\n\n"

        for (heading, sectionBody) in parsed.sections {
            if AdapterHelpers.droppedSections.contains(heading.lowercased()) { continue }
            let renamed = AdapterHelpers.renameIdentityHeading(heading)
            out += "## \(renamed)\n\n\(sectionBody)\n\n"
        }

        result.artifacts.append(BuildArtifact(
            relativePath: "SOUL.md",
            contents: out.trimmingCharacters(in: .newlines) + "\n",
            sourceDescription: "Identity ← \(file.filename)",
            designation: file.designation))
    }

    // MARK: Context → AGENTS.md

    private func buildAgents(from store: CanonicalStore, into result: inout BuildResult) {
        let ctx = store.includedFiles(.context)
        guard !ctx.isEmpty else {
            result.warnings.append("No Context file selected — AGENTS.md not generated.")
            return
        }

        // Order: role → domain → team.
        let sorted = AdapterHelpers.sortedContext(ctx)

        var out = ""
        out += "<!-- Generated by Personal OS Studio · OpenClaw adapter -->\n"
        out += "> SOUL.md rules take precedence over anything below.\n\n"

        var strongest = Designation.pub

        for file in sorted {
            let raw = store.read(file)
            let (_, body) = Frontmatter.split(raw)
            let parsed = MarkdownSections.parse(body)
            if file.designation.strength > strongest.strength { strongest = file.designation }

            let type = (file.contextType ?? "context").capitalized
            out += "# \(type) context\n\n"
            if !parsed.banner.isEmpty {
                out += AdapterHelpers.firstBlockquoteLine(parsed.banner) + "\n\n"
            }
            for (heading, sectionBody) in parsed.sections {
                if AdapterHelpers.droppedSections.contains(heading.lowercased()) { continue }
                out += "### \(heading)\n\n\(sectionBody)\n\n"
            }
        }

        result.artifacts.append(BuildArtifact(
            relativePath: "AGENTS.md",
            contents: out.trimmingCharacters(in: .newlines) + "\n",
            sourceDescription: "Context ← \(sorted.map(\.filename).joined(separator: ", "))",
            designation: strongest))
    }

    // MARK: Skills → skills/<name>/SKILL.md

    private func buildSkills(from store: CanonicalStore, into result: inout BuildResult) {
        let skills = AdapterHelpers.sortedSkills(
            store.includedFiles(.skills).filter { !$0.isTemplate && $0.name != nil })

        for file in skills {
            guard let name = file.name else { continue }
            let raw = store.read(file)
            let (fields, body) = Frontmatter.split(raw)
            let parsed = MarkdownSections.parse(body)

            let trigger = parsed.section("Trigger") ?? ""
            let description = AdapterHelpers.firstSentence(trigger)

            var out = "---\n"
            out += "name: \(name)\n"
            out += "description: \(description)\n"
            out += "---\n\n"
            out += AdapterHelpers.provenanceComment(fields) + "\n\n"
            if !parsed.banner.isEmpty { out += AdapterHelpers.firstBlockquoteLine(parsed.banner) + "\n\n" }

            // Keep Inputs, Procedure, Output verbatim. Drop authoring artifacts.
            for keep in ["Inputs", "Procedure", "Output"] {
                if let s = parsed.section(keep) {
                    out += "## \(keep)\n\n\(s)\n\n"
                }
            }

            result.artifacts.append(BuildArtifact(
                relativePath: "skills/\(name)/SKILL.md",
                contents: out.trimmingCharacters(in: .newlines) + "\n",
                sourceDescription: "Skill ← \(file.filename)",
                designation: file.designation))
        }
    }

    // MARK: Memory → MEMORY.md + memory/<name>.md

    private func buildMemory(from store: CanonicalStore, into result: inout BuildResult) {
        let mem = store.includedFiles(.memory)

        // Index file (MEMORY.md).
        if let index = mem.first(where: { $0.filename.uppercased().contains("MEMORY") }) {
            let raw = store.read(index)
            let (_, body) = Frontmatter.split(raw)
            result.artifacts.append(BuildArtifact(
                relativePath: "MEMORY.md",
                contents: body.trimmingCharacters(in: .newlines) + "\n",
                sourceDescription: "Memory index ← \(index.filename)",
                designation: index.designation))
        }

        // Persistent entries.
        let entries = mem.filter { $0.entryType != nil && $0.name != nil }
        for file in entries {
            guard let name = file.name else { continue }
            let raw = store.read(file)
            let (fields, body) = Frontmatter.split(raw)
            let parsed = MarkdownSections.parse(body)
            let entryBody = parsed.section("Entry") ?? body

            var out = "---\n"
            out += "name: \(name)\n"
            if let et = fields["entry_type"] { out += "entry_type: \(et)\n" }
            if let d = fields["description"] { out += "description: \(d)\n" }
            out += "---\n\n"
            if !parsed.banner.isEmpty { out += AdapterHelpers.firstBlockquoteLine(parsed.banner) + "\n\n" }
            out += entryBody.trimmingCharacters(in: .newlines) + "\n"

            result.artifacts.append(BuildArtifact(
                relativePath: "memory/\(name).md",
                contents: out,
                sourceDescription: "Memory ← \(file.filename)",
                designation: file.designation))
        }
    }

    // MARK: Connections (informational only)

    private func noteConnections(from store: CanonicalStore, into result: inout BuildResult) {
        let conns = store.includedFiles(.connections).filter { !$0.isTemplate }
        guard !conns.isEmpty else { return }
        result.warnings.append("Connections are configured in openclaw.json, not workspace files. \(conns.count) connection file(s) selected — review and register them manually per the adapter; Studio does not edit openclaw.json.")
    }
}
